### ISSUE TITLE
Patch version release broke compatibility

### ISSUE THREAD

**Issue by kushudai** [rust-cli/config-rs#594]
Going from 0.14.0 to 0.14.1 breaks deserialization of previously de-serializable files.
File:
```
kafka_config:
  brokers: []
  security_protocol: ""
  sasl_mechanisms: ""
  sasl_username: ~
  sasl_password: ~

kafka_config:
  brokers: [kafka:9092]
  security_protocol: plaintext
  sasl_mechanisms: PLAIN
  sasl_username: admin
  sasl_password: admin
```

This would parse with 0.14.0 but no longer does with 0.14.1

I believe swap to yaml-rust2 changed this behavior.
