### ISSUE TITLE
can't get item in array at v0.14

### ISSUE THREAD

**Issue by rise0chen** [rust-cli/config-rs#609]
```yml
Student:
  - Name: Tom
  - Name: Bob
```
```rust
println!("{}", cfg.get_string("Student[0].Name").unwrap())
```

error:
```
called `Result::unwrap()~on an “Err`value: configuration property "student[0].name" not found
```
